# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: cypress/base:8

    working_directory: ~/repo

    steps:
      - checkout
    
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps

      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running E2E tests with JUnit reporter
          command: npm run test-junit
      - store_test_results:
          path: junit-results
      - store_artifacts:
          path: cypress/screenshots
  
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/repo

    steps:
      - checkout
    
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: AWS EC2 deploy
          command: |
            chmod 400 geokey.pem
            ssh -o StrictHostKeyChecking=no -i geokey.pem ubuntu@geonotebook.com "./geonotebook/deploy.sh"


workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test

